server:
  port: 8989
  servlet:
    context-path: /TangSong
    jsp:
      init-parameters:  #jsp开发模式部署  支持热部署  更改jsp不必重新启动服务器
        development: true
spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.117.132:3306/tangsong?characterEncoding=UTF-8&serverTimezone=GMT
    username: root
    password: 520Qiao.
  redis:
    host: 192.168.117.132
    port: 7000
    database: 0
#    pool:    连接池有问题
#      max-active: 8
#      max-wait: -1
#     max-idle: 8
#      min-idle: 0
# 和es相关的配置
  data:
    elasticsearch:
      cluster-nodes: 192.168.117.132:9300


mybatis:
  mapper-locations: classpath:com/qiao/mapper/*.xml #mapper文件地址
  type-aliases-package: com.qiao.entity #声明别名